// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// export default sidebars;

module.exports = {
  tutorialSidebar: [
    'markdown',
    {
      type: 'category',
      label: 'Docusaurus',
      link: {
        type: 'doc',
        id: 'docusaurus', // same page when clicking the category
      },
      items: [
        {
          type: 'doc',
          id: 'docusaurus/types',
          label: 'Types Document',
        },
        {
          type: 'doc',
          id: 'docusaurus/markdown',
          label: 'Markdown Document',
        },
        {
          type: 'doc',
          id: "docusaurus/navbar",
          label: "Navbar Document",
        },
        {
          type: 'doc',
          id: "docusaurus/sidebar",
          label: "Sidebar Document",
        },
        {          
          type: 'doc',
          id: "docusaurus/search",
          label: "Search Document",
        },
        {
          type: 'doc',
          id: "docusaurus/breadcrumbs",
          label: "Breadcrumbs Document",
        },
        {
          type: 'doc',
          id: "docusaurus/links",
          label: "Links Document",
        },
        {
          type: 'doc',
          id: "docusaurus/media",
          label: "Media Document",
        },
        {
          type: 'doc',
          id: "docusaurus/versions",
          label: "Versioning Document",
        }
      ],
    },
    {
      type: 'category',
      label: 'API',
      link: {
        type: 'doc',
        id: 'api', // same page when clicking the category
      },
      items: [
      ]
    }
  ],
};
